version: '3.1'

services:
  single-pass:
    image: prom/single
    build: ./single-pass
    ports:
      - 9999:9999
    restart: always
    deploy:
     placement:
       constraints:
          - node.role == worker
  rest-api:
    image: prom/rest
    build: ./rest-api
    ports:
      - 8888:8888
    restart: always
    deploy:
     placement:
       constraints:
          - node.role == manager